"""add_policy_pull_requests_and_review_actions_tables

Revision ID: 145151c462dc
Revises: 2f8512577d69
Create Date: 2026-06-10 15:21:00.326709+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '145151c462dc'
down_revision: Union[str, None] = '2f8512577d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_pull_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('obligation_id', sa.String(length=36), nullable=False),
    sa.Column('gap_analysis_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('gap_description', sa.Text(), nullable=False),
    sa.Column('proposed_amendment', sa.Text(), nullable=False),
    sa.Column('regulatory_citation', sa.Text(), nullable=True),
    sa.Column('suggested_owner_id', sa.String(length=36), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('before_text', sa.Text(), nullable=False),
    sa.Column('after_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gap_analysis_id'], ['gap_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggested_owner_id'], ['responsibility_owners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_pull_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_pull_requests_gap_analysis_id'), ['gap_analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_pull_requests_obligation_id'), ['obligation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_pull_requests_suggested_owner_id'), ['suggested_owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_pull_requests_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('review_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_pull_request_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('reviewer_label', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('modified_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_pull_request_id'], ['policy_pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_actions_policy_pull_request_id'), ['policy_pull_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_actions_policy_pull_request_id'))

    op.drop_table('review_actions')
    with op.batch_alter_table('policy_pull_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_pull_requests_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_policy_pull_requests_suggested_owner_id'))
        batch_op.drop_index(batch_op.f('ix_policy_pull_requests_obligation_id'))
        batch_op.drop_index(batch_op.f('ix_policy_pull_requests_gap_analysis_id'))

    op.drop_table('policy_pull_requests')
    # ### end Alembic commands ###
