"""add_policy_mappings_table

Revision ID: 056edbbbb1c4
Revises: d9139ac5e8a1
Create Date: 2026-06-10 14:44:47.988443+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056edbbbb1c4'
down_revision: Union[str, None] = 'd9139ac5e8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('obligation_id', sa.String(length=36), nullable=False),
    sa.Column('policy_document_id', sa.String(length=36), nullable=True),
    sa.Column('document_chunk_id', sa.String(length=36), nullable=True),
    sa.Column('policy_excerpt', sa.Text(), nullable=True),
    sa.Column('mapping_rationale', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('is_no_match', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_mappings_obligation_id'), ['obligation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_mappings_policy_document_id'), ['policy_document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_mappings_policy_document_id'))
        batch_op.drop_index(batch_op.f('ix_policy_mappings_obligation_id'))

    op.drop_table('policy_mappings')
    # ### end Alembic commands ###
