"""add_gap_analyses_table

Revision ID: 2f8512577d69
Revises: 056edbbbb1c4
Create Date: 2026-06-10 15:09:33.725758+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f8512577d69'
down_revision: Union[str, None] = '056edbbbb1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gap_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('obligation_id', sa.String(length=36), nullable=False),
    sa.Column('policy_mapping_id', sa.String(length=36), nullable=True),
    sa.Column('coverage_status', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('source_citations', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_mapping_id'], ['policy_mappings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gap_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gap_analyses_obligation_id'), ['obligation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gap_analyses_policy_mapping_id'), ['policy_mapping_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gap_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gap_analyses_policy_mapping_id'))
        batch_op.drop_index(batch_op.f('ix_gap_analyses_obligation_id'))

    op.drop_table('gap_analyses')
    # ### end Alembic commands ###
